language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lsturgeon0906/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lsturgeon0906/docker-react yarn test -- --coverage
