# Start cloudbuild
# we just want to install and run tests for now
steps:
  # build the docker image
  - name: gcr.io/cloud-builders/docker
    id: buildinstaller
    args:
      [
        "build",
        "-t",
        "gcr.io/test",
        "-f",
        "Dockerfile",
        "."
      ]
  # this step pushes the image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/test"
  # fires the jest tests of the app so far
  - name: 'gcr.io/cloud-builders/docker'
    id: test
    args:
      - "run"
      - "CI=true"
      - "gcr.io/test"
      - "npm"
      - "run"
      - "test"
      - "--"
      - "--coverage"
